apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: one
  namespace: foo-bar
spec:
  encryptedData:
    a.datasource.password: AQC8RD9BqVsWbeNGP0akGZSZM4PFOzZzTGpXpJclN+U21udib5pJOMfN1u5u7/bmV8A8zFt24c0N29dcWVN9V0lRg7mJ+vbuD7uct/QgRbFFQr6wQtalhWCoZjQNQ/I6va4EGZzS06ulj7ezTlkNfIl1PLWDWqGw+XLvAjmqWb1ZoGzkGW8PwmBrZERBhf7ugd4/l766dtm6o8HTW+kYJAOI0aTSwekCbDwHhwCjcTQXJdfXSN/ZU/SBkOA6tCzRoKaDum36IDEiyjtKmwkuwnVaj4mH84TPgieROE+bSUApvfWQX9EreUDoML66K5glamcpcSrbzHlkz4IxyAxvuK7qOcS5FxhNKYnrKxZD7wAOXbxrXPD9sAf0SdN9Dje1CqALnbPCnYLe89xHMHEzLgknFmtFWudos9N/TO6Ot+KpaUbZnHJMmw9GrEgbOb3d3KaRgndXtT2jMw==
  template:
    metadata:
      creationTimestamp: null
      name: one
      namespace: foo-bar
status: {}

