apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-class
data:
  envType: BAR
  URL_COMMON: https://basic:0.0.0.1
  no_proxy: ""
  NO_PROXY: ""
  URL_FOOBAR_HOST: https://0.0.0.1/tobeoverwritten